### ISSUE TITLE
data-issue: chinese shown on the english page

### ISSUE THREAD

**Issue by erchaves** [mplusmuseum/mplusmuseum-collections-explorer#53]
On a single object page, the design shows two languages -- both english and chinese. If we want to show both, we need to have both in the API. At the moment, we can't make a call for each language.

![screen shot 2018-12-03 at 6 15 23 pm](https://user-images.githubusercontent.com/302309/49407966-72b4bc80-f728-11e8-9302-523a48a086ea.png)

related ticket: internationalization
https://github.com/mplusmuseum/mplusmuseum-collections-explorer/issues/6

**Comment by revdancatt** [comment]
I think just removing them is the best solution.

The other option is to make two calls, the first to get all the data, the 2nd specifying the other language and just the title/date.

Both of those options don't involve any API changes.

The 3rd option is for me to also include the "other" language for titles and dates in the API. So the selected language title shows up in the language fields as normal and _if_ the other language translation is different (because sometimes the other option doesn't exist) then it can be included like `titleOther` or something.

**Comment by micahwalter** [comment]
We can't remove the Chinese here. It's integral to the design and follows the M+ Stories design as well as a nod to how they display labels in galleries. 

Is it possible to add a parameter to the field you are requesting and ask it for additional data? ... like

```
{ (lang:en)
    title {
      lang: tc
    }
}
````
